import base64
from typing import Any

import httpx

from agents.template_renderer import build_preview_document
from config import get_settings


async def validate_github_token(token: str) -> bool:
    settings = get_settings()
    async with httpx.AsyncClient(timeout=30) as client:
        res = await client.get(
            f"{settings.github_api_url}/user",
            headers={
                "Accept": "application/vnd.github+json",
                "Authorization": f"Bearer {token}",
                "X-GitHub-Api-Version": "2022-11-28",
            },
        )
        return res.is_success


def resolve_github_token(user_token: str | None) -> str | None:
    settings = get_settings()
    if user_token and user_token.strip():
        return user_token.strip()
    if settings.github_token.strip():
        return settings.github_token.strip()
    return None


async def export_project_to_github(
    token: str,
    repo_name: str,
    app: dict[str, str],
    *,
    description: str | None = None,
    is_private: bool = False,
    existing_repo: bool = False,
) -> dict[str, Any]:
    settings = get_settings()
    sanitized = (
        repo_name.strip()
        .lower()
        .replace(" ", "-")
    )
    import re

    sanitized = re.sub(r"[^a-z0-9-_]", "-", sanitized)
    sanitized = re.sub(r"-+", "-", sanitized).strip("-")
    if not sanitized:
        raise ValueError("仓库名称无效")

    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    async with httpx.AsyncClient(timeout=60) as client:
        user_res = await client.get(f"{settings.github_api_url}/user", headers=headers)
        if not user_res.is_success:
            raise ValueError("GitHub Token 无效或已过期")
        user = user_res.json()
        login = user["login"]

        if not existing_repo:
            create_res = await client.post(
                f"{settings.github_api_url}/user/repos",
                headers={**headers, "Content-Type": "application/json"},
                json={
                    "name": sanitized,
                    "description": description or "Generated by Atoms Demo",
                    "private": is_private,
                    "auto_init": False,
                },
            )
            if not create_res.is_success:
                err = create_res.json()
                msg = err.get("message", "创建仓库失败")
                if create_res.status_code != 422 or "already exists" not in msg:
                    raise ValueError(msg)

        files = {
            "index.html": build_preview_document(app),
            "styles.css": app["css"],
            "scripts.js": app["js"],
            "README.md": f"# {sanitized}\n\n由 Atoms Demo 多智能体流水线生成。\n",
        }

        uploaded: list[str] = []
        for path, content in files.items():
            encoded_path = httpx.URL(path).raw_path.decode()
            contents_url = f"{settings.github_api_url}/repos/{login}/{sanitized}/contents/{path}"

            sha = None
            existing_res = await client.get(contents_url, headers=headers)
            if existing_res.is_success:
                sha = existing_res.json().get("sha")

            put_res = await client.put(
                contents_url,
                headers={**headers, "Content-Type": "application/json"},
                json={
                    "message": f"Update {path}" if sha else f"Add {path}",
                    "content": base64.b64encode(content.encode()).decode(),
                    **({"sha": sha} if sha else {}),
                },
            )
            if not put_res.is_success:
                err = put_res.json()
                raise ValueError(err.get("message", f"上传 {path} 失败"))
            uploaded.append(path)

    return {
        "repoUrl": f"https://github.com/{login}/{sanitized}",
        "repoName": sanitized,
        "filesUploaded": uploaded,
    }
